development:
  adapter: postgresql
  encoding: unicode
  database: <%= $secret[:db][:database] %>
  host: <%= $secret[:db][:host] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= $secret[:db][:username] %>
  password: <%= $secret[:db][:password] %>

test:
  adapter: postgresql
  encoding: unicode
  database: <%= $secret[:db][:database] %>
  host: <%= $secret[:db][:host] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= $secret[:db][:username] %>
  password: <%= $secret[:db][:password] %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= $secret[:db][:database] %>
  host: <%= $secret[:db][:host] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= $secret[:db][:username] %>
  password: <%= $secret[:db][:password] %>
